### ISSUE TITLE
react-addons-test-utils is deprecated

### ISSUE THREAD

**Issue by bengillies** [sheepsteak/react-shallow-testutils#32]
React 15.5 deprecates react-addons-test-utils. Everything here still seems to work fine, but the dependencies in `package.json` need updating.

**Comment by sheepsteak** [comment]
Thanks for letting me know. I'l have this done in the next day or so.

**Comment by mlabrum** [comment]
Any update? :)

**Comment by sheepsteak** [comment]
Haha, I've done the actual work (have a look at the [react-15-5-4](https://github.com/sheepsteak/react-shallow-testutils/tree/react-15-5-4) branch.

I was just wondering about how to handle the versioning. I think since anyone using this new version will have to add/remove dependencies when they update I should probably make it a new major version.

I'll try and get a v3 published tonight and that will be for React v15.5.0+

**Comment by bengillies** [comment]
> I was just wondering about how to handle the versioning.

Agreed. I think it's a breaking change for those people still on React < 15.5.

**Comment by sheepsteak** [comment]
Fixed in [v3.0.0](https://github.com/sheepsteak/react-shallow-testutils/releases/tag/v3.0.0).
